
theme: jekyll-theme-merlot
name: Diana

description: solo es para hacer ejercicios de ejemplos, ejercicios de prueba... 

avatar: https://avatars1.githubusercontent.com/u/56721094?s=460&v=4

markdown: kramdown
highlighter: rouge
permalink:

version: v1.1.0

exclude:
  -README.md
